import type { Metadata } from 'next'
import "../components/globals.css"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-Br">
      <body >{children}</body>
    </html>
  )
}
